=== died/XsdTest/XsdTest/Xsd/POResponseAndAmendmentv1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			This Schema defines adidas PO Confirmation Message
			Version Number: 1.0
			Date of creation: 1 Aug 2018
		</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="CommonDataTypesv1_0.xsd"/>
	<xsd:element name="POResponseAndAmendment" type="POResponseAndAmendmentType"/>
	
	<xsd:complexType name="buyerType">
		<xsd:sequence>
			<xsd:element name="buyerName" type="string255" />
			<xsd:element name="buyerAddressLine1" type="string255" />
			<xsd:element minOccurs="0" name="buyerAddressLine2" type="string255" />
			<xsd:element minOccurs="0" name="buyerAddressLine3" type="string255" />
			<xsd:element minOccurs="0" name="buyerAddressLine4" type="string255" />
			<xsd:element minOccurs="0" name="buyerCity" type="string255" />
			<xsd:element minOccurs="0" name="buyerProvince" type="string255" />
			<xsd:element name="buyerCountryCode" type="countryCodeEnumeration" />
			<xsd:element minOccurs="0" name="buyerPostalCode" type="string9" />
			<xsd:element minOccurs="0" name="buyerContactPerson" type="string50"/>
			<xsd:element minOccurs="0" name="buyerContactTelNumber" type="string50"/>
			<xsd:element minOccurs="0" name="buyerContactEmail" type="string100"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="POResponseAndAmendmentType">
				<xsd:sequence>
					<xsd:element name="POResponsePurpose" type="POResponsePurposeEnumeration"/>
					<xsd:element name="PONumber" type="string50"/>
					<xsd:element name="POVersionNumber" type="nonNegativeInteger10"/>
					<xsd:element name="POResponseVersionNumber" type="nonNegativeInteger10"/>
					<xsd:element name="messageGenerationDateTime" type="xsd:dateTime"/>
					<xsd:element name="latestUpdateDateTime" type="xsd:dateTime"/>
					<xsd:element minOccurs="0" name="headerRemarks" type="string350"/>
					<xsd:element name="sender" type="senderType"/>
					<xsd:element name="recipient" type="string255"/>
					<xsd:element name="buyer" type="buyerType"/>
					<xsd:element name="sellerName" type="string255"/>
					<xsd:element maxOccurs="3000" name="POLineItem" type="POLineItemType"/>
				</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="POLineItemType">
		<xsd:sequence>
			<xsd:element name="lineItemNumber" type="xsd:positiveInteger"/>
			<xsd:element name="requestDate" type="xsd:date"/>
			<xsd:element minOccurs="0" name="lineRemarks" type="string350"/>
			<xsd:element name="materialReferenceNumber" type="string100"/>
			<xsd:element name="confirmedDeliveryDate" type="xsd:date"/>
			<xsd:element name="confirmedDeliveryQty" type="float3"/>
			<xsd:element minOccurs="0" name="updatedDeliveryDate" type="xsd:date"/>
			<xsd:element minOccurs="0" name="updatedDeliveryQty" type="float3"/>
			<xsd:element minOccurs="0" name="lastShipmentConfirmedDeliveryDate" type="xsd:date"/>
			<xsd:element minOccurs="0" name="lastShipmentConfirmedDeliveryQty" type="float3"/>
			<xsd:element minOccurs="0" name="lastShipmentUpdatedDeliveryDate" type="xsd:date"/>
			<xsd:element minOccurs="0" name="lastShipmentUpdatedDeliveryQty" type="float3"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="senderType">
		<xsd:sequence>
			<xsd:element name="senderName" type="string255" />
			<xsd:element name="senderPerson" type="string255" />
		</xsd:sequence>
	</xsd:complexType>
	
</xsd:schema>

=== died/XsdTest/XsdTest/bin/Debug/test.xml
<?xml version="1.0" encoding="utf-8"?><POResponseAndAmendment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="POResponseAndAmendmentv1_0.xsd"><POResponsePurpose>PO Confirmation</POResponsePurpose><PONumber>0123456798</PONumber><POVersionNumber>0</POVersionNumber><POResponseVersionNumber>0</POResponseVersionNumber><messageGenerationDateTime>2019-01-21T12:01:46.1279305+08:00</messageGenerationDateTime><latestUpdateDateTime>2019-01-21T12:01:46.1279305+08:00</latestUpdateDateTime><headerRemarks>Check markings on cases, there was a problem with past orders. This is general information only, not to be processed by your system.</headerRemarks><sender><senderName>T1ABC</senderName><senderPerson>Sam Jones</senderPerson></sender><recipient>T2ABCD</recipient><buyer><buyerName>T1 Supplier Company Limited</buyerName><buyerAddressLine1>48/F, Kodak House, 123 Java Road, North Point</buyerAddressLine1><buyerAddressLine2>address line 2</buyerAddressLine2><buyerAddressLine3>address line 3</buyerAddressLine3><buyerAddressLine4>address line 4</buyerAddressLine4><buyerCity>Hong Kong</buyerCity><buyerProvince>Guangdong</buyerProvince><buyerCountryCode>HK</buyerCountryCode><buyerPostalCode>000</buyerPostalCode><buyerContactPerson>Mr John Smith</buyerContactPerson><buyerContactTelNumber>852 1234 5678</buyerContactTelNumber><buyerContactEmail>j.smith@email.com</buyerContactEmail></buyer><sellerName>T2 Supplier Company Limited</sellerName><POLineItem><lineItemNumber>1</lineItemNumber><requestDate>2018-07-01</requestDate><lineRemarks>Supply of material to be as per samples approved on 2017-12-14</lineRemarks><materialReferenceNumber>3432545532</materialReferenceNumber><confirmedDeliveryDate>2019-01-17</confirmedDeliveryDate><confirmedDeliveryQty>100.000</confirmedDeliveryQty></POLineItem></POResponseAndAmendment>
